default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml
        args: [--unsafe]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.8.1
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.280"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude: "tests/openiapi/typescript_converter/test_converter"
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        exclude: "_templates"
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.0
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
        args: ["--use-tuple"]
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.16.5
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        exclude: "tools|docs"
        args: ["--show-traceback"]
        additional_dependencies:
          [
            pydantic,
            pydantic-settings,
            jinja2,
            rich,
            click,
            rich-click,
            polyfactory,
            pydantic_openapi_schema,
            structlog,
            pytest,
            pytest-docker,
            litestar,
            types-click,
            types-passlib,
            types-click,
            types-PyYAML,
            uvicorn,
            prometheus_client,
            hypothesis,
          ]
