name: Pip Audit

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          allow-prereleases: true

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.11
          allow-python-prereleases: true
          cache: true

      - name: Install dependencies
        run: pdm install -G:all

      - name: Set pythonpath
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run pip audit
        uses: pypa/gh-action-pip-audit@v1.0.8
