name: Documentation Building

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          allow-prereleases: true

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.12
          allow-python-prereleases: true
          cache: true

      - name: Install dependencies
        run: pdm install -G:all

      - name: Fetch gh pages
        run: git fetch origin gh-pages --depth=1

      - name: Build docs
        run: pdm run python tools/build_docs.py docs-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build
