name: Latest Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.12
          allow-python-prereleases: true
          cache: true

      - name: Install dependencies
        run: pdm install
# TODO: Learn then move to Hatchling build/PDM publish... whatever
#      - name: publish
#        shell: bash
#        run: |
#          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
#          poetry publish --build --no-interaction
